"""change_cv_coverletter_to_json

Revision ID: 09652646e631
Revises: f6d4bffa3484
Create Date: 2026-05-03 20:27:08.975509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09652646e631'
down_revision: Union[str, None] = 'f6d4bffa3484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Convert existing TEXT data to a JSON array with a paragraph content block,
    # then change the column type to JSON.
    op.execute(
        """
        UPDATE analysis_results
        SET optimised_cv = json_build_array(json_build_object('type', 'paragraph', 'content', optimised_cv))::text
        WHERE optimised_cv IS NOT NULL;
        """
    )
    op.execute(
        """
        UPDATE analysis_results
        SET cover_letter = json_build_array(json_build_object('type', 'paragraph', 'content', cover_letter))::text
        WHERE cover_letter IS NOT NULL;
        """
    )
    op.alter_column('analysis_results', 'optimised_cv',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='optimised_cv::json')
    op.alter_column('analysis_results', 'cover_letter',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='cover_letter::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'cover_letter',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('analysis_results', 'optimised_cv',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
