"""make cv_id nullable in analysis and job_applications

Revision ID: ec57fb4fda15
Revises: 09652646e631
Create Date: 2026-05-14 16:42:24.129405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec57fb4fda15'
down_revision: Union[str, None] = '09652646e631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'cv_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('job_applications', 'cv_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_applications', 'cv_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analysis_results', 'cv_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
